### ISSUE TITLE
no device discover

### ISSUE THREAD

**Issue by lacrimosa2k2** [mabunixda/node-red-contrib-alexa-home#27] opened 2019-06-23 18:21 UTC
the alexa local doesnt work with the echo dot 3.gen so i try it with this, or cant handle the 3.gen?
when i search for devices, the alexa controller says setup requested and nothing found

**Comment by tt2g89** [comment] 2019-06-24 06:14
+1 
with Echo 1. Gen and Dot 1. Gen, also tried with the android app and the web app, but cannot discover. Controller says setup requested.

**Comment by mabunixda** [comment] 2019-06-24 06:19
@tt2g89  @lacrimosa2k2 how many devices are configured in your node-red right now ?

**Comment by lacrimosa2k2** [comment] 2019-06-24 06:21
only one for testing

**Comment by tt2g89** [comment] 2019-06-24 06:28
Same here.

**Comment by tt2g89** [comment] 2019-06-24 06:31
Just to be sure:
I add the Controller and do not link it to any element. I also add Alexa home, name it and link it to an action, correct?
Alexa home has two connectors to work as either an input or an output device, also correct?

BR

**Comment by mabunixda** [comment] 2019-06-24 07:00
@tt2g89 correct yes .. 

i gonna try to reproduce this with my gen 2 devices

**Comment by lacrimosa2k2** [comment] 2019-06-24 07:04
![asd32qerdsf](https://user-images.githubusercontent.com/28703161/59998134-f69bab00-965e-11e9-9577-e5f04a691bcf.JPG)
status with the amazon echo dot 3. gen

**Comment by mabunixda** [comment] 2019-06-24 07:23
i just got the same problem with my deployment at home which was running now since release 1.0 very smooth and much more reactive then the 0.x version.

**Comment by mabunixda** [comment] 2019-06-25 06:14
The discovery is working again by yesterday ... i did not make any code changes in this part.

**Comment by lacrimosa2k2** [comment] 2019-06-25 06:16
> 
> 
> The discovery is working again by yesterday ... i did not make any code changes in this part.

tested, the controller  says, setup requested again

**Comment by tt2g89** [comment] 2019-06-25 07:20
G'Morning,
Since yesterday I use red node in a docker container inside my loxberry installation.
From then on the Controller just said ok, but doesn't find new devices either.
In the logs I saw, that SSDP is being used by red node, too.
Which ports are needed to have a working communication?
I opened 1880 and 1900 for the container.

**Comment by mabunixda** [comment] 2019-06-25 08:44
1880/tcp is node-red, 1900/udp is ssdp. At the moment only those 2 ports are used. I am also running node-red as docker deployment, but within kubernetes... 

My development setup is also within a docker container and i must run the docker container on the host network because udp broadcast does not work correct with network overlays - as far as i was researching the last time ( a year ago at least .. ) 

You can define an environment variable DEBUG and set it to "node-ssdp:server" to get debug messages from the ssdp communication.

**Comment by tt2g89** [comment] 2019-06-25 09:06
1900/udp is already in use by ssdp from loxberry -.-
0.0.0.0:1900... This could be another tiny problem and I'm not that Linux-super-specialist, that I can solve it. :(

I'm also using the loxone node. :)

**Comment by mabunixda** [comment] 2019-06-25 12:05
i assume that 172.17.0.3 is your docker container ip? 
How are you starting the container? on host network or overlay? 

@lacrimosa2k2 can you turn on debug logging in node-red and try a device discovery? there should be some logs what calls are made

**Comment by tt2g89** [comment] 2019-06-25 12:53
> 
> 
> i assume that 172.17.0.3 is your docker container ip?
That's correct.
> How are you starting the container? on host network or overlay?
At the moment via bridge. Should I change to host?

**Comment by mabunixda** [comment] 2019-06-25 12:55
@tt2g89 yeah please retry with host

**Comment by tt2g89** [comment] 2019-06-25 13:45
@mabunixda It isn't possible to connect to the network driver host via container. Maybe a misunderstanding from my side?
Errormessage from Portainer:"Failure
container cannot be disconnected from host network or connected to host network"

**Comment by lacrimosa2k2** [comment] 2019-06-25 14:16
> 
> 
> i assume that 172.17.0.3 is your docker container ip?
> How are you starting the container? on host network or overlay?
> 
> @lacrimosa2k2 can you turn on debug logging in node-red and try a device discovery? there should be some logs what calls are made

this debug? 
`

node-red.0 | 2019-06-25 16:14:36.521 | debug | 25 Jun 16:14:36 - [info] Started flows
-- | -- | -- | --
node-red.0 | 2019-06-25 16:14:36.513 | debug | 25 Jun 16:14:36 - [info] Assigning alexa-home nodes to this controller
node-red.0 | 2019-06-25 16:14:36.504 | debug | 25 Jun 16:14:36 - [info] [alexa-home-controller:Alexa Controller] Alexa Controller - alexa-home - Starting SSDP
node-red.0 | 2019-06-25 16:14:36.481 | debug | 25 Jun 16:14:36 - [info] Starting flows
node-red.0 | 2019-06-25 16:14:36.472 | debug | 25 Jun 16:14:36 - [info] Stopped flows
node-red.0 | 2019-06-25 16:14:36.464 | debug | 25 Jun 16:14:36 - [info] Alexa Local Hub closing done...
node-red.0 | 2019-06-25 16:14:36.419 | debug | 25 Jun 16:14:36 - [info] Stopping flows
node-red.0 | 2019-06-25 16:13:42.035 | debug | 25 Jun 16:13:42 - [info] Server now running at http://127.0.0.1:1880/
node-red.0 | 2019-06-25 16:13:41.839 | debug | 25 Jun 16:13:41 - [info] Started flows
node-red.0 | 2019-06-25 16:13:41.829 | debug | 25 Jun 16:13:41 - [info] Assigning alexa-home nodes to this controller
node-red.0 | 2019-06-25 16:13:41.724 | debug | 25 Jun 16:13:41 - [info] [alexa-home-controller:Alexa Controller] Alexa Controller - alexa-home - Starting SSDP
node-red.0 | 2019-06-25 16:13:40.146 | debug | 25 Jun 16:13:40 - [info] Starting flows
node-red.0 | 2019-06-25 16:13:39.802 | debug | 25 Jun 16:13:39 - [info] Flows file     : /opt/iobroker/iobroker-data/node-red/flows.json

`

**Comment by mabunixda** [comment] 2019-06-25 15:09
@lacrimosa2k2 yes this one - and now in the timeframe when the discover process is running

@tt2g89 hm - i am using docker from commandline and not by loxberry ... i can give it a review in the evening...

**Comment by lacrimosa2k2** [comment] 2019-06-25 15:13
> 
> 
> @lacrimosa2k2 yes this one - and now in the timeframe when the discover process is running
> 
> @tt2g89 hm - i am using docker from commandline and not by loxberry ... i can give it a review in the evening...

iots the time from the discovery, this snipet repeats

**Comment by tt2g89** [comment] 2019-06-27 10:24
Hi all,
I reinstalled my whole loxberry and installed red node outside docker. Works fine now.
It was not possible to join the host network within portainer.
And as you already wrote  @mabunixda overlay networks do not work correctly for some reason.

**Comment by mabunixda** [comment] 2019-07-01 07:38
for loxone you have to work with  functions now, because on is now a switch of payload object
```
return { payload: ( msg.payload.on ? "on"  : "off") }
```
or for blinds i use following shared function
```
if(msg.payload.command == "off" || !msg.payload.on) {
    msg.payload = "FullUp";
} else if(msg.payload.command == "color") {
        msg.payload = "Shade"
} else if(msg.payload.command == "dim") {
        msg.payload = "Auto";
} else {
    msg.payload = "FullDown";
}
return msg;
```

**Comment by tt2g89** [comment] 2019-07-01 21:14
Hi @mabunixda,
many thanks, that works well. Don't you use dimmable lights on Loxone? I'm still a bad scripter, but I'll try to use the blinds-function and change it to dim the lights correctly. ;)
The blinds work well, thanks again!!! :) The wording is quite funny, when I tell Alexa "Rollo blau" and it starts the automatic mode. :D

**Comment by mabunixda** [comment] 2019-07-02 05:14
@tt2g89 yes the wording is funny - you can change the dim and color command to make more sense ;-) 

@lacrimosa2k2 do you still have problems on detection? How is node-red running and which generation of alexa devices do you own?

**Comment by lacrimosa2k2** [comment] 2019-07-04 19:41
@mabunixda 
yes, node-red is running on iobroker
the alexa is the 3. generation

**Comment by Ikswoknib** [comment] 2019-07-04 22:04
Hello,
I'm having some similar setup:
Loxberry with Docker installation and ioBroker with node-red in a container.
I am using an MacVLAN Network for the Docker container, but i am not able to get it to work.
The Discovery always says no devices found. I tried to use an Echo 1. Gen, Echo 3. Gen and over the WebPage...

Is MacVLAN also not working ?

What does the "setup requested" mean ?

**Comment by mabunixda** [comment] 2019-07-05 06:55
setup requested means, that a device/application requested the setup.xml provided via upnp. 
The discover process looks as follows:
* alexa: udp broadcast on upnp 
* node-red: udp answer of node with link to setup.xml ( /alexa-home/setup.xml )
* alexa: requests setup.xml to get base information about the "hub"
* alexa: afterwards a http request is made to a api endpoint where all devices get listed ( /api/<username>/lights )

@Ikswoknib but you get the "setup requested" information displayed? Then the udp broadcast on upnp is working in your setup and alexa devices already request the setup.xml
Can you try to go on debug logging on node-red? This would display which device is requesting the setup.xml which is related to "setup requested" 

It is hard to test a change for 3rd gen, when you do not own such a device :-(

**Comment by Ikswoknib** [comment] 2019-07-05 13:27
hello,

here is the Debug Log:

`
undefined2019-07-05 15:23:11.485  - info: host.1ac3a1a41b87 object change system.adapter.node-red.0
--
2019-07-05 15:23:11.486  - info: host.1ac3a1a41b87 stopInstance system.adapter.node-red.0
2019-07-05 15:23:11.497  - info: node-red.0 kill node-red task
2019-07-05 15:23:12.097  - info: node-red.0 node-red exited with 0
2019-07-05 15:23:12.490  - info: host.1ac3a1a41b87 stopInstance timeout "1000 system.adapter.node-red.0 killing pid  11236
2019-07-05 15:23:12.551  - info: host.1ac3a1a41b87 instance system.adapter.node-red.0 terminated with code 0 (OK)
2019-07-05 15:23:15.028  - info: host.1ac3a1a41b87 instance system.adapter.node-red.0 started with pid 11516
2019-07-05 15:23:18.217  - debug: node-red.0 objectDB connected
2019-07-05 15:23:18.395  - debug: node-red.0 statesDB connected
2019-07-05 15:23:18.551  - info: node-red.0 starting. Version 1.7.1 in /opt/iobroker/node_modules/iobroker.node-red, node: v8.16.0
2019-07-05 15:23:24.157  - error: hm-rpc.1 adapter disabled
2019-07-05 15:23:24.342  - error: host.1ac3a1a41b87 instance system.adapter.hm-rpc.1 terminated with code 3 (Adapter disabled or invalid config)
2019-07-05 15:23:24.343  - info: host.1ac3a1a41b87 Do not restart adapter system.adapter.hm-rpc.1 because disabled or deleted
2019-07-05 15:23:25.155  - info:  node-red.0 Starting node-red: --max-old-space-size=128  /opt/iobroker/node_modules/node-red/red.js -v --settings  /opt/iobroker/iobroker-data/node-red/settings.js
2019-07-05 15:23:31.262  - debug: node-red.0 5 Jul 15:23:31 - [info]
Welcome to Node-RED
===================
2019-07-05 15:23:31.272  - debug: node-red.0 5 Jul 15:23:31 - [info] Node-RED version: v0.19.6
2019-07-05 15:23:31.274  - debug: node-red.0 5 Jul 15:23:31 - [info] Node.js  version: v8.16.0
2019-07-05 15:23:31.275  - debug: node-red.0 5 Jul 15:23:31 - [info] Linux 4.14.98-v7+ arm LE
2019-07-05 15:23:33.688  - debug: node-red.0 5 Jul 15:23:33 - [info] Loading palette nodes
2019-07-05 15:23:37.060  - warn: node-red.0 5 Jul 15:23:37 - [warn] rpi-gpio : Cannot find Pi RPi.GPIO python library
2019-07-05 15:23:45.239  - debug: node-red.0 5 Jul 15:23:45 - [info] Polymer started at /polymer
2019-07-05 15:23:45.848  - debug: node-red.0 5 Jul 15:23:45 - [info] Dashboard version 2.15.5 started at /ui
2019-07-05 15:23:47.091  - debug: node-red.0 5 Jul 15:23:47 - [info] Settings file  : /opt/iobroker/iobroker-data/node-red/settings.js
2019-07-05 15:23:47.101  - debug: node-red.0 5 Jul 15:23:47 - [info] Context store  : 'default' [module=memory]
2019-07-05 15:23:47.115  - warn: node-red.0 5 Jul 15:23:47 - [info] User directory : /opt/iobroker/iobroker-data/node-red/
5 Jul 15:23:47 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
5 Jul 15:23:47 - [info] Flows file     : /opt/iobroker/iobroker-data/node-red/flows.json
2019-07-05 15:23:47.262  - debug: node-red.0 5 Jul 15:23:47 - [info] Server now running at http://127.0.0.1:1880/
2019-07-05 15:23:47.543  - debug: node-red.0 5 Jul 15:23:47 - [info] Starting flows
2019-07-05 15:23:47.622  - debug: node-red.0 5 Jul 15:23:47 - [info] [alexa-home-controller:Alexa Controller] Alexa Controller - alexa-home - Starting SSDP
2019-07-05 15:23:48.233  - debug: node-red.0 5 Jul 15:23:48 - [info] Assigning alexa-home nodes to this controller
2019-07-05 15:23:48.297  - debug: node-red.0 5 Jul 15:23:48 - [info] Started flows
2019-07-05 15:23:48.572  - debug: node-red.0 objectDB connected
2019-07-05 15:23:48.721  - debug: node-red.0 statesDB connected
2019-07-05 15:24:08.353  - debug: node-red.0 system.adapter.admin.0: logging false
2019-07-05 15:24:08.359  - debug: node-red.0 system.adapter.admin.0: logging false
2019-07-05 15:24:10.194  - debug: node-red.0 system.adapter.admin.0: logging true
2019-07-05 15:24:10.203  - debug: node-red.0 system.adapter.admin.0: logging true
`

The log is taken after restarting the node Red Adapter in iobroker.
I can't see anything in there ...
The "Alexa contoller" goes after 2 seconds from "ok" to "setup requestet", without making an Device Discovery of Alexa

**Comment by tt2g89** [comment] 2019-07-06 08:51
> Hi @mabunixda,
> many thanks, that works well. Don't you use dimmable lights on Loxone?
I'm sorry to ask again, but I'm not able to get a function to work, that makes dimming of lights work. :(

**Comment by cernst1980** [comment] 2019-07-17 21:00
node-red Basic-Authentication needs to be disabled. Now it works for me...

**Comment by fklement** [comment] 2019-07-28 14:54
> node-red Basic-Authentication needs to be disabled. Now it works for me...

Didn't worked for me.  
I hadn't set up any authentication for my node-red.  

```bash
$ curl http://192.168.178.87:1880/auth/login
{}%
```

Am I missing something?

**Comment by mabunixda** [comment] 2019-07-31 13:03
@fklement at default no component at node-red is using an authentication

On the dev branch there is already a complete new version coming up using a different mechanism to propagate the information to alexa.
But i already read that also the new devices with screens are using a different mechanism to detect devices and i do not own such a devices :(

**Comment by HanSolo72** [comment] 2019-08-04 20:00
I have the same problem. I had Version 0.3.5 installed, but last week I reinstalled my complete ioBroker and Node-Red-Environment, also this Alexa adapter in it's version 1.0.4. Since then device discovery didn't work. Now I deleted it and installed the old version 0.3.5 (command as below). Now it works again.

I will not update until the error is fixed. If I can help you, tell me what information you need. I have two Echo Dot V2.

Commands for installing the old version (for Node-Red with ioBroker):
cd /opt/iobroker/node_modules/iobroker.node-red/node_modules/
npm install node-red-contrib-alexa-home@0.3.5

**Comment by mabunixda** [comment] 2019-08-05 05:47
@HanSolo72 yeah i already rewrote this part in the dev branch ... but there is still a limitation on redeploying which does not always occure :(

**Comment by mabunixda** [comment] 2019-08-28 14:45
@cernst1980 with 1.1.0 also works with basic authentication cofnigured node-red installations

**Comment by mabunixda** [comment] 2019-08-28 16:02
I gonna close this issue because it duplicates #16  for now

**Closed by mabunixda** 2019-08-28 16:02 UTC
Labels: bug, duplicate
